export default function () {

    return [
                {
                    photo: "photos/Men1.jpg",
                    class: "Mshoes",
                    name: "shoe1",
                    msg: "This shoe is cool ",
                    showMore: true,
                },
                {
                    photo: "photos/Men2.jpg",
                    class: "Mshoes",
                    name: "shoe2",
                    msg: "This shoe is awsome ",
                    showMore: false,
                },
                {
                    photo: "photos/Men3.jpg",
                    class: "Mshoes",
                    name: "shoe3",
                    msg: "This shoe is white ",
                    showMore: false,
                },
                {
                    photo: "photos/Men4.jpg",
                    class: "Mshoes",
                    name: "shoe4",
                    msg: "This shoe is blue ",
                    showMore: false,
                },
                {
                    photo: "photos/Men5.jpg",
                    class: "Mshoes",
                    name: "shoe5",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/Men6.jpg",
                    class: "Mshoes",
                    name: "shoe6",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/women1.jpg",
                    class: "WShoes",
                    name: "shoe7",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/women2.jpg",
                    class: "WShoes",
                    name: "shoe8",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/women3.jpg",
                    class: "WShoes",
                    name: "shoe9",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/women4.jpg",
                    class: "WShoes",
                    name: "shoe10",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/women5.jpg",
                    class: "WShoes",
                    name: "shoe11",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/women6.jpg",
                    class: "WShoes",
                    name: "shoe12",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/Kids1.jpg",
                    class: "KShoes",
                    name: "shoe13",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/Kids2.jpg",
                    class: "KShoes",
                    name: "shoe14",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/Kids3.jpg",
                    class: "KShoes",
                    name: "shoe15",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/Kids4.jpg",
                    class: "KShoes",
                    name: "shoe16",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/Kids5.jpg",
                    class: "KShoes",
                    name: "shoe17",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
                {
                    photo: "photos/Kids6.jpg",
                    class: "KShoes",
                    name: "shoe18",
                    msg: "this shoe is nice ",
                    showMore: false,
                },
    ];
}


